### ISSUE TITLE
Cannot Create Scenario

### ISSUE THREAD

**Issue by chriswunsch00** [getyoti/ios-sdk-button#1]
### Discussion

Whilst integrating the ButtonSDK and following the ReadME instructions, the provided code example does not compile. 

#### Issue

The following source does not compile:

```swift
guard let url = URL.setCallbackBackendURL(URL(string: “add_your_callback_url_here”) else{
    return
}
```

The quotes used are incorrectly formatted but also the following compiler error:

```swift
Type 'URL' has no member 'setCallbackBackendURL'
```

I'm assuming this is available via an extension on `URL` ?

**Comment by casperkclee** [comment]
Note: This API is no longer available since version 2.0
